# Generated by Django 3.0.6 on 2020-05-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(max_length=250, upload_to='docs/excel/file1')),
                ('file2', models.FileField(max_length=250, upload_to='docs/excel/file2')),
            ],
        ),
    ]
