# Generated by Django 3.0.6 on 2020-05-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='excelfiles',
            table='Excel Files',
        ),
    ]
