# Generated by Django 3.0.6 on 2020-05-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200527_1701'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='excelfiles',
            table='Excel File',
        ),
    ]
