# Generated by Django 3.0.6 on 2020-05-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200527_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExcelFiles',
            new_name='ExcelFilePair',
        ),
    ]
